config/routes.rb
DW3::Application.routes.draw do
  
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
  
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  resources :users

  resources :dworlds

  get "dworld/home"
  get "dworld/about"
  get "dworld/portfolio"
  get "dworld/news"
  get "dworld/contact"
  post "dworld/contact"
  get "dworld/index"

  root 'dworld#home'

end

app/models/dworld.rb
class Dworld < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dworld_controller.rb
class DworldController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def news
  end

  def contact
    @name = params[:Name]
    @email = params[:"Email Address"]
    @question = params[:Questions]
    
    if params[:commit]
      flash.now[:error] = ""
      if @name.nil? || @name.empty?
        flash.now[:error] << "Please enter Name.</br>"
      end
      if @email.nil? || @email.empty?
        flash.now[:error] << "Please enter Email.</br>"
      end
    end
  end
end

app/controllers/dworlds_controller.rb
class DworldsController < ApplicationController
  before_action :set_dworld, only: [:show, :edit, :update, :destroy]

  # GET /dworlds
  # GET /dworlds.json
  def index
    @dworlds = Dworld.all
  end

  # GET /dworlds/1
  # GET /dworlds/1.json
  def show
  end

  # GET /dworlds/new
  def new
    @dworld = Dworld.new
  end

  # GET /dworlds/1/edit
  def edit
  end

  # POST /dworlds
  # POST /dworlds.json
  def create
    @dworld = Dworld.new(dworld_params)

    respond_to do |format|
      if @dworld.save
        format.html { redirect_to @dworld, notice: 'Info was successfully send to us.' }
        format.json { render action: 'show', status: :created, location: @dworld }
      else
        format.html { render action: 'new' }
        format.json { render json: @dworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dworlds/1
  # PATCH/PUT /dworlds/1.json
  def update
    respond_to do |format|
      if @dworld.update(dworld_params)
        format.html { redirect_to @dworld, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dworlds/1
  # DELETE /dworlds/1.json
  def destroy
    @dworld.destroy
    respond_to do |format|
      format.html { redirect_to dworlds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dworld
      @dworld = Dworld.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dworld_params
      params.require(:dworld).permit(:name, :email, :question, :datesend)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to(dworld_portfolio_path, notice: 'Logged out, Thank You.')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
 #def user_params
 # params.require(:user).permit(:email, :crypted_password, :salt)
 #end
    
      private

#-- We also need to allow UsersController receive form attributes:-->
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def show_params
    html = "<div style='border:1px green solid; margin:10px;padding:10px;'>"
    html += '<heading><h2>Info Send to Us</heading><br/></h2>'
    
    params.each do |key, value|
      html += "<h3>#{key}: #{value} <br/></h3>" if (key != 'authenticity_token' && key != 'utf8')
      
  end
  html += '</div>'
  return html.html_safe
 end
 
 def things_to_do( links )
    # key = URL, value = body
    html = "<ul>"
    links.each do |url, body |
      html += "<li>" + link_to( body, url) + "</li>"
    end
    html +="</ul>"
    return html.html_safe

  end
end

app/helpers/dworld_helper.rb
module DworldHelper
end

app/helpers/dworlds_helper.rb
module DworldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dworld/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dharma World Temple USA Contact</title>
  <%= stylesheet_link_tag    "contact", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->
	
    <!--end header-->

	</header>

<!--

<% content_for :title do %>
	<% end %>

<%= form_tag do %>
	<table>
		<TR>
			<TD><h1></h1></TD>
		</TR>	<br/>
		
				<TR>
			<TD><h2>Contact Us with Questions Below</h2></TD>
		</TR><br/>	
		<TR>
			<TD><h3><%= label_tag "Your Name"%></h3></TD>
			<TD><h3><%= text_field_tag 'Name' %></h3></TD>
		</TR>
		<br/>
	
		<TR>
			<TD><h3><%= label_tag "Your Email Address"%></h3></TD>
			<TD><h3><%= email_field_tag 'Email Address' %></h3></TD>
		</TR>
		<br/>
		
		<TR>
			<TD><h3><%= label_tag "Your Question"%></h3></TD>
			<TD><h3><%= text_area_tag 'Question' %></h3></TD>
		</TR>
		<br/>
		
		<TR>
			<TD></TD>
			<TD><%= submit_tag 'Submit your question' %></TD>
		</TR>
		<br/>
	
		</table>
		<br/>	

</br/>		
-->
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1510.8072723146244!2d-73.8223539243753!3d40.770501830958054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5f71fa637513012b!2sDharma+World!5e0!3m2!1sen!2sus!4v1395253333130" width="600" height="450" frameborder="0" style="border:0"></iframe>
		
<!--start menu-->

	<nav>
    <ul>
    <li><a href="http://dharmaworldusa.x10.mx/index.html">Home</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/about.html">About</a></li>
	<li><a href="http://dharmaworldusa.x10.mx/member.html">Members</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/news.html">News</a></li>
    <li><a href="http://infinite-oasis-5251.herokuapp.com/dworlds/new">Contact</a></li>

    </ul>
    </nav>
<!--end menu-->

	
<% end %>
	
	<div style="border:0px black solid">
		<%#= "Name Submitted: " + @name %><br/>
		<%#= "Email Submitted: " + @email %><br/>
		<p></p>
		<%#= "We will get back to you ASAP. Thanks for your interest, " + @name + "." %><br/>
		<%#= params.inspect %>
		<p></p>
		</div>
<% if params[:commit] != nil %>
<%= show_params %>
<% end %>

   </div>
   <!--end container-->
      <!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldusa.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="https://sites.google.com/site/masterliuus/">M[LiuUS]</a> </div> 
   </div>
   </footer>
   <!--end footer-->
   

app/views/dworld/portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>About Us</title>
  <%= stylesheet_link_tag    "members", media: "all" %>
  <%= javascript_include_tag "application" %> 
  <%= csrf_meta_tags %>
  
  <!--nivo slider script-->
  
   <script type="text/javascript" src="/assets/jquery-2.0.2.js"></script>
   <script type="text/javascript" src="/assets/jquery.nivo.slider.js"></script>
  
</head>
<body>

<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg' %></a>    

	<!--end logo-->
	
   <!--start menu-->

	<nav>
    <ul>
    <li><a href="http://dharmaworldusa.x10.mx/index.html">Home</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/about.html">About</a></li>
	<li><a href="http://dharmaworldusa.x10.mx/member.html">Members</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/news.html">News </a></li>
    <li><a href="/dworld/portfolio.html">Login</a></li>

    </ul>
    </nav>
	<!--end menu-->
	

	

   
   <!--start holder-->

   <div class="holder_content">
   <h4>Dharma World Temple USA Login Page</h4>
   <section class="group1">
<!--   
   <h1>Master 大师</h1>
   <%= image_tag 'icon1.png'%>
   
   	  <!-- start login menu-->
<h1>
  <div id="navilogin">
    <% if current_user %>
      <%#= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%#= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
 </h1>
  
  <!--end login menu -->
  
<!-- 
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   
   <a href=""><span class="button">Read more</span></a>
   </section>
-->

<!--   
   <section class="group2">
   <h1>Master 大师 </h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>
   
   <section class="group3">
   <h1>Master 大师</h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>
   <a href=""><span class="button">Read more</span></a>
    
   </section>
   
      <section class="group1">
   <h1>Master 大师</h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>

   
   <section class="group2">
   <h1>Master 大师 </h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>
   
   <section class="group3">
   <h1>Master 大师</h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>
   <a href=""><span class="button">Read more</span></a>
    
   </section>
   
   

 
   </div>
   <!--end holder-->
   
    <!--end header-->
	</header>

  
   
   </div>
   <!--end container-->
   
   <!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldus.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="https://sites.google.com/site/masterliuus/">M[LIU]</a> </div> 
   </div>
   </footer>
   <!--end footer-->
 <!-- Free template distributed by http://freehtml5templates.com -->  

<%= yield %>

</body>
</html>

app/views/dworlds/_form.html.erb
<%= form_for(@dworld) do |f| %>
  <% if @dworld.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dworld.errors.count, "error") %> prohibited this dworld from being saved:</h2>

      <ul>
      <% @dworld.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= f.label :name %> 名稱<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <h2><%= f.label :email %> 您的電郵<br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <h2><%= f.label :question %> 查問建議.<br>
    <%= f.text_area :question, :cols=> 48, :rows => 12 %></h2>
  </div>
  <div class="field">
    <%#= f.label :datesend %><br>
    <%#= f.datetime_select :datesend %>
  </div>
  <div class="actions">
    <%= f.submit "Send 遞交"%>
    <br><br>
  </div>
<% end %>

app/views/dworlds/edit.html.erb
<h1>Editing dworld</h1>

<%= render 'form' %>

<%= link_to 'Show', @dworld %> |
<%= link_to 'Back', dworlds_path %>

app/views/dworlds/index.html.erb
<body style="background:#60AB88">
<font face="Arial" color="black">	
   <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->

<h1>Dharma World Temple USA Inquiry Listing</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Question</th>
      <th>Datesend</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dworlds.each do |dworld| %>
      <tr>
        <td><%= dworld.name %></td>
        <td><%= dworld.email %></td>
        <td><%= dworld.question %></td>
        <td><%= dworld.datesend %></td>
        <td><%= link_to 'Show', dworld %></td>
        <td><%= link_to 'Edit', edit_dworld_path(dworld) %></td>
        <td><%= button_to 'Destroy', dworld, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Main Page', dworld_portfolio_path %>

app/views/dworlds/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dharma World Temple USA Contact Info</title>
  <%= stylesheet_link_tag    "contact", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->
	
    <!--end header-->

	</header>



<% content_for :title do %>
	<% end %>

<%= form_tag do %>
	<table>
		<TR>
			<TD><h1></h1></TD>
		</TR>	<br/>
		
				<TR>
			<TD><h2></h2></TD>
		</TR><br/>	
		<TR>
			<TD><h3>Contact Us with Questions Below
			</h3></TD>
			<TD><h3></h3></TD>
		</TR>
		<br/>
	

	
		</table>
		<br/>	
		
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1510.8072723146244!2d-73.8223539243753!3d40.770501830958054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5f71fa637513012b!2sDharma+World!5e0!3m2!1sen!2sus!4v1395253333130" width="600" height="450" frameborder="0" style="border:0"></iframe>
		
<!--start menu-->

	<nav>
    <ul>
    <li><a href="http://dharmaworldusa.x10.mx/index.html">Home</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/about.html">About</a></li>
	<li><a href="http://dharmaworldusa.x10.mx/member.html">Members</a></li>
    <li><a href="http://dharmaworldusa.x10.mx/news.html">News</a></li>
    <li><a href="http://infinite-oasis-5251.herokuapp.com/dworlds/new">Contact</a></li>
    <li><a href="/dworld/portfolio.html">Master Login</a></li>

    </ul>
    </nav>
<!--end menu-->

	
<% end %>
	
<%= render 'form' %>

   </div>
   <!--end container-->

<!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.DharmaWorldUSA.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="https://sites.google.com/site/masterliuus/">[LiuUS] Hak.Aython</a> </div> 
          
   <!-- Start Login / DB Link >     
          <li><a href="/dworlds">.</a></li>  
   <-- End Login / DB Link -->     
           
   </div>
   </footer>
   <!--end footer-->

				<%#= link_to 'Back', dworlds_path %>

app/views/dworlds/show.html.erb
<p id="notice"><%= notice %></p>

<body style="background:#60AB88">
<font face="Arial" color="black">	
   <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>  

<p>
  <strong>Thank You for Contacting Dharma World Temple USA.</strong>
  
</p>

<p>
  <strong>Name:</strong>
  <%= @dworld.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dworld.email %>
</p>

<p>
  <strong>Question:</strong>
  <%= @dworld.question %>
</p>

<p>
  <strong>Datesend: Today</strong>
  <%= @dworld.datesend %>
</p>

<%#= link_to 'Edit', edit_dworld_path(@dworld) %> |
<%#= link_to 'Return Home', dworld_contact_path %>

    <li><a href="http://dharmaworldusa.x10.mx/index.html">Back To Dharma World Temple USA Website</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DharmaWorld</title>

</head>
<body>


  <%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<body style="background:#80BFFF">
<font face="Arial" color="black">		
   <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->

<h1>Dharma World Temple USA Login Page</h1>

<%= render 'form' %>
<p></p>

<%= link_to 'Back', dworld_home_path %>
</font>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <!-- <div class="field">
    <%= f.label :crypted_password %><br>
    <%= f.text_field :crypted_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %> -->
    <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
	</div>
	<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
	</div>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<body style="background:#AA60A8">
<font face="Arial" color="black">	
   <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->


<h1>Dharma World Temple USA Login Users List</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Create New User', new_user_path %>
<br>
<%= link_to 'Database', dworlds_path %>
<br>
<%= link_to 'Back to Main Page for Logout', dworld_portfolio_path %>
<br>
</font> 

app/views/users/new.html.erb
<body style="background:#AA60A8">
<font face="Arial" color="black">	
   <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dworldlogo1b.jpg'%></a>    

	<!--end logo-->
<h1>New user</h1>

<%= render 'form' %>
<p>
	
</p>
<%= link_to 'Back to Main Page', dworld_portfolio_path %>
</font>>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>